FROM node:23-alpine3.20 AS installer

WORKDIR /app
COPY package.json package-lock.json .
RUN npm install

COPY . .


FROM node:23-alpine3.20 AS dev

WORKDIR /app
COPY --from=installer /app /app
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]


FROM node:23-alpine3.20 AS builder

WORKDIR /app
COPY --from=installer /app /app

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build


FROM busybox:1.36 AS prod

WORKDIR /app
COPY --from=builder /app/dist .

EXPOSE 3000
CMD ["busybox", "httpd", "-f", "-v", "-p", "3000"]
