export const funnySlogansHaha = [
	"Suomen wappuradiot yhdessä paikassa",
	"Wapun epävirallinen aggregoija",
	"The Ultimate Wappu Aggregator",
	"Wappu taskussasi",
	"Klara vappen",
	"Bara vatten",
	"Gaudeamus igitur, iuvenes dum sumus!",
	"Juokaa simaa",
	"Onko sima jo käymässä?",
	"Sitä kissa ostaisi",
	"Vappu on joka torstai",
	"Räyh t:wappre gator 🐊",
	"Solidia jäsää",
	"Hosted by Mikon koti-internet",
	"Pythonin ja TypeScriptin epäpyhä liitto",
	"Wireless Application Protocol",
	"[object Object]",
	"{{ slogan }}",
	"$slogan",
	"Moi äiti",
	'wappuradio"; drop table channels; --',
	"köbbub vhaava",
	"keksin lisää huomenna nyt pää tyynyyn 1000fps",
	"Kaikkien maiden proletaarit, liittykää yhteen!",
	"Kõigi maade proletaarlased, ühinege!",
	"Shoutout to tippaleipä connoisseurs",
	"Tippaleipä on pahaa",
	"Connecting people",
	"Wappu - redefined",
	"Oon toi kissa",
	"Bob ei syö pepperonipizzaa",
	"Valmistunut tai tapettu",
	"Sponsored by pitkä viikonloppu",
	"Wappu Wide Web",
	"Och detsamma på svenska",
	"Haloo",
	"Kuuluuko?",
	"Shoutout to TKO-äly",
	"Shoutout to AOP&PHK",
	"It's a feature",
	"Special thanks to aa ii äm äl",
	"Älä laita tomaattia",
	"Tervetuloa Laitilan Munamarkkinoille 14.-15.6.",
	"Melkein WCAG 2.1 AA kompliantti!",
	"Sitten alkoi unettomuus.",
];
