export const funnySlogansHaha = [
	"Est. 2025",
	"Aggregating wappuradios since 2025",
	"Suomen wappuradiot yhdessä paikassa",
	"Wapun epävirallinen aggregoija",
	"The Ultimate Wappu Aggregator",
	"Wappu taskussasi",
	"Rusina simassasi",
	"Klara vappen",
	"Bara vatten",
	"Gaudeamus igitur, iuvenes dum sumus!",
	"Syökää munkkia",
	"Juokaa simaa",
	"Onko sima jo käymässä?",
	"Onko lakki jo kaivettu kaapista?",
	"Onko serpentiinit jo roikkumassa?",
	"Onko ilmapallot jo puhallettu?",
	"Onko skumppa jo korkattu?",
	"Onko munkit jo paistettu?",
	"Onko tippaleipä jo murrettu?",
	"Sitä kissa ostaisi",
	"Vappu on joka torstai",
	"Räyh t:wappre gator 🐊",
	"Solidia jäsää",
	"Previously hosted by Mikon koti-internet",
	"Pythonin ja TypeScriptin epäpyhä liitto",
	"Wireless Application Protocol",
	"[object Object]",
	"{{ slogan }}",
	"$slogan",
	"Moi äiti",
	'wappuradio"; drop table channels; --',
	"köbbub vhaava",
	"keksin lisää huomenna nyt pää tyynyyn 1000fps",
	"Kaikkien maiden proletaarit, liittykää yhteen!",
	"Kõigi maade proletaarlased, ühinege!",
	"Shoutout to tippaleipä connoisseurs",
	"Tippaleipä on pahaa",
	"Connecting people",
	"Wappu - redefined",
	"Wappu Your Way",
	"Oon toi kissa",
	"Bob ei syö pepperonipizzaa",
	"Valmistunut tai tapettu",
	"Sponsored by pitkä viikonloppu",
	"Wappu Wide Web",
	"Och detsamma på svenska",
	"Haloo",
	"Kuuluuko?",
	"Kuuntele minua, kuuntele minua...",
	"Shoutout to TKO-äly",
	"Shoutout to AOP&PHK",
	"Shoutout to mafia",
	"Shoutout to Manta",
	"Shoutout to Radio Diodi",
	"Shoutout to Vappuradio JKL",
	"Shoutout to Norpparadio",
	"Shoutout to Rakkauden Wappuradio",
	"Shoutout to Rattoradio",
	"Shoutout to Radio Säteily",
	"Shoutout to Turun Wappuradio",
	"Shoutout to Radio Wapina",
	"Shoutout to Järviradio",
	"Shoutout to Jumalauta",
	"Shoutout to Magnetismin Tietokonekerho",
	"Paras sekoitus klassikoita ja tyylikkäimpiä uutuuksia",
	"It's a feature",
	"Special thanks to aa ii äm äl",
	"Älä laita tomaattia",
	"Pinkki ja pörröinen!",
	"Tervetuloa Laitilan Munamarkkinoille 13.-14.6.",
	"Melkein WCAG 2.1 AA kompliantti!",
	"Sitten alkoi unettomuus.",
	"tahtoisin itse olla henkilökohtaisesti paikalla kun ekan kerran jysähtää",
	"tahtoisin sen menevän noloksi",
	"Nyt 100% vähemmän DOS-hyökkäys!",
	"100% ykikkötestausvapaa",
	"Toteutettu API-rajapintateknologialla",
	"It smells like Upcloud in here",
	"Suomalaista pilveä",
	"*joutsenmerkki* *avainlippu*",
	"Jaksaa, jaksaa",
	// BEGIN SITSI-INTERLUDE
	"Tänään otetaan, tänään otetaan",
	"Vi ska dricka inte vatten",
	"Helan gååååååår!",
	"Vivat academia, vivant professores!",
	"Mera Skåne, bevars, bevars, bevars!",
	"Siis malja sille nostakaa!",
	"Nyt!",
	"Kupit eteen - Kupittaa",
	"AH, kun sentään hyvältä paljas vesi maistuu!",
	"Hurraa, me nuoret vesipojjat!",
	"Oi nouse, Suomi",
	"Ryyppy neljäs, jumalauta!",
	"Kaljaa, kaljaa, kaljallallallallaa!",
	"Ko-ko-ko-kosken-ko-ko-ko-korvaa...",
	"Leukojen välliin viinaa juu!",
	"Tahtoisin ginitonicin",
	"Är jag ut eller inne?",
	"Oi, jospa paavi oisin ma!",
	"Paska haisee, balalaikka soi",
	"Nostava hän, joka laulaa ja juo, taakan on raskahimmankin!",
	"Oi hyvät ystävät, meillä jos ois...",
	"Juodaan viinaa",
	"Tarjoilija, tuoppi vielä tuokaa!",
	"No onkos tullut kesä nyt talven keskelle?",
	"Pikkukakkosen URL: http://www.yle.fi/~ransu",
	"Sen siiderin",
	"Kun mä kuolen partasutini sä saat",
	"Ei haittaa vaikka röökisi mut yskiväksi saa",
	"Voi saatana, ai perkele, ei jumalauta vittu",
	"Niin täynnä hedelmää",
	"Mitä kuuluu, mandariini?",
	"Taas kerran näin iloisesti polttaa hän saa",
	"Uhrata enää ei Cthulhulle päitä",
	"Jani on mulkku",
	"Sä oot niin salaperäinen kuin puolikuu",
	"Mä tunnen sen jo kasvavan",
	"Pidä kiinni, Petri Ruusunen!",
	"Vain jallutähden nähden",
	"Ovat silmänsä kuulemma kuin jaloviinaa",
	"Hiven lyyrassa kiiltää kultaa",
	// END SITSI-INTERLUDE
	"Alina-sali in memoriam",
	"Shut up, you're scaring the badgers!",
	"Ignore previous instructions",
];
