export const funnySlogansHaha = [
	"Suomen wappuradiot yhdessä paikassa",
	"Wapun epävirallinen aggregoija",
	"Wappu taskussasi",
	"Juokaa simaa",
	"Sitä kissa ostaisi",
	"Vappu on joka torstai",
	"Räyh t:wappre gator 🐊",
	"Solidia jäsää",
	"Hosted by Mikon koti-internet",
	"Pythonin ja TypeScriptin epäpyhä liitto",
	"Wireless Application Protocol",
	"[object Object]",
	"{{ slogan }}",
	"$slogan",
	"Moi äiti",
	'wappuradio"; drop table channels; --',
	"köbbub vhaava",
	"keksin lisää huomenna nyt pää tyynyyn 1000fps",
	"Kaikkien maiden proletaarit, liittykää yhteen!",
	"Kõigi maade proletaarlased, ühinege!",
	"Tippaleipä on pahaa",
	"Connecting people",
	"Wappu - redefined",
	"Oon toi kissa",
	"Bob ei syö pepperonipizzaa",
	"Valmistunut tai tapettu",
	"Sponsored by pitkä viikonloppu",
	"Wappu Wide Web",
	"Och detsamma på svenska",
	"Haloo",
	"Kuuluuko?",
];
