name: 'Docker: Build & Publish'

on:
  workflow_call:
    inputs:
        container-name:
          type: string
          required: true
        working-directory:
          type: string
          default: '.'
        dockerfile:
          type: string
          default: 'Dockerfile'
        build-args:
          type: string

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.container-name }}
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ inputs.working-directory }}"
          file: "{{context}}/${{ inputs.dockerfile}}"
          build-args: ${{ inputs.build-args }}
          push: ${{ github.ref_name == github.event.repository.default_branch && github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        if: github.ref_name == github.event.repository.default_branch && github.event_name == 'push'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ inputs.container-name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
